add background image
js-tasks-ru/htmlcss-20241107_yulya-malova pull request #14
Opened 2024-11-27 17:11 UTC by julia-ma98

2024-11-27 17:12 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-28 21:43 UTC, GSemikozov requested changes

2024-11-28 21:43 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    @media(min-width:400px) {
это - лишний запрос, данная картинка ставится просто по умолчанию

2024-11-29 14:14 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-29 14:31 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-30 12:54 UTC, GSemikozov approved these changes

2024-11-30 12:54 UTC, merged