Dz template
js-tasks-ru/htmlcss-20241107_yulya-malova pull request #21
Opened 2024-12-08 20:42 UTC by julia-ma98

2024-12-08 20:42 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-12 14:52 UTC, GSemikozov requested changes

2024-12-12 14:52 UTC, GSemikozov commented on components/dz-footer/footer.css
> +   grid-area: footer;
области размечаем через элементы блока, которые задает эти области

2024-12-12 14:52 UTC, GSemikozov commented on components/dz-header/header.css
> +    grid-area: header;
и тут

2024-12-12 14:52 UTC, GSemikozov commented on components/dz-sidebar/sidebar.css
> +    grid-area: sidebar;
и тут

2024-12-12 14:52 UTC, GSemikozov commented on components/dz-sidebar/sidebar.css
> +    padding: 36px 165px 0 165px;
по краям - лишние, у нас же есть container

2024-12-12 14:52 UTC, GSemikozov commented on components/dz-template-desc/template-desc.css
> +    margin: 36px 165px 0 0;
а справа точно надо?)

2024-12-13 19:05 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-13 20:06 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-16 18:53 UTC, GSemikozov requested changes

2024-12-16 18:53 UTC, GSemikozov commented on components/dz-header/header.css
> +    grid-area: header;
неа) мы же не знаем что родитель 100% грид с таким темплейтом. Надо через page - .page__header и тд

2024-12-16 18:53 UTC, GSemikozov commented on components/dz-template-desc/template-desc.css
> +    grid-area: template;
см выше, такая же проблема

2024-12-23 10:49 UTC, GSemikozov requested changes

2024-12-23 10:49 UTC, GSemikozov commented on pages/template.html
> +                        <div class="sidebar">
именно здесь - page__sidebar

2024-12-23 10:49 UTC, GSemikozov commented on pages/template.html
> +                            <div class="template__desc page__template">
лучше завернуть в отдельный div с page__template

2024-12-23 10:49 UTC, GSemikozov commented on pages/template.html
> +                    <footer class="footer footer__template page__footer">Reusable component library</footer>
footer__template -> footer_template (это модификатор)

2024-12-23 10:49 UTC, GSemikozov commented on components/dz-page/page.css
> +.page__footer {
тут оставляем только grid-area, остальное уносим в сам футер и там описываем как его элемент (footer__text или как-то так)

2024-12-25 09:59 UTC, GSemikozov requested changes

2024-12-25 09:59 UTC, GSemikozov commented on pages/template.html
> +                    <footer class="footer footer_template footer__text page__footer">Reusable component library</footer>
footer__text - внутри, блок не может быть одновременно своим элементом)

2024-12-30 14:35 UTC, GSemikozov approved these changes

2024-12-30 14:35 UTC, merged