add tooltip
js-tasks-ru/htmlcss-20241107_yulya-malova pull request #8
Opened 2024-11-19 15:37 UTC by julia-ma98

2024-11-19 15:37 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-19 15:42 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-19 16:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-20 16:18 UTC, GSemikozov requested changes

2024-11-20 16:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 50px;
top + left удалим

2024-11-21 08:58 UTC, julia-ma98 commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 50px;
удалила

2024-11-21 09:50 UTC, GSemikozov approved these changes

2024-11-21 09:50 UTC, merged